trigger:
- master

stages:
- stage: Copy
  displayName: 'Download a copy artifact'
  jobs:
  - job: DownloadCopy
    displayName: 'Download'
    pool:
      vmImage: 'Ubuntu 18.04'
    steps:
    - task: CopyFiles@2
      inputs:
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
    
- stage: 'BuildTest'
  displayName: 'Build and Test'
  variables:
    GOVERSION: '1.15'   # Version of Go tools used for building and testing
    CGO_ENABLED: '0'      # Disable cgo to get a static binary
    GOOS: 'linux'
    GOARCH: 'amd64'
  jobs:
  - job: BuildTestBackend
    displayName: 'Build and Test Go Backend'
    pool:
      vmImage: 'Ubuntu 18.04'
    steps:
    - task: GoTool@0
      inputs:
        version: $(GOVERSION)
      displayName: 'Install and select Go version $(GOVERSION)'
    
    - task: Go@0
      inputs:
        command: 'build'
        workingDirectory: '$(Build.ArtifactStagingDirectory)/main' 